# -*- coding: utf-8 -*-
"""Walmart_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPq82TRYJ-K-2EyFsmA3hsCVOEaT1uP2

Usecase-1 Load all three csv datasets in Pandas Data frames and display first 5 records.
"""

from google.colab import files

ls

data = files.upload()

import pandas as pd

customers_list = ['custno','firstname','lastname','gender','age','profession','contactNo',
'emailId','city','state','isActive','createdDate','UpdatedDate']

products_list = ['productno','productName','Description','isActive','createdDate','UpdatedDate']

transactions_list = ['txnno','txndate','custno','amount','productno','spendby']

df_customers = pd.read_csv('customers.csv',names=customers_list)
df_customers.head(6)

df_products = pd.read_csv('products.csv',names=products_list)
df_products.head(6)

df_transactions = pd.read_csv('transactions.csv', names= transactions_list)
df_transactions.head(6)

"""Usecase-2 Display only those customers from CSV_s1, who purchased more than 3 products

"""

df_1 = pd.merge(df_customers,df_transactions)
df_2 = df_1.groupby('custno').count()
df_3 = df_customers.set_index('custno')
df_3['Product_purchased'] = df_2['txnno']
df_3[df_3['Product_purchased']>3]

"""Usecase-3 Display top 5 most demanded products from CSV_s1"""

df_4 = pd.merge(df_products,df_transactions)
df_5 = df_4.groupby('productno').count()
df_6 = df_products.set_index('productno')
df_6['Product_Sold'] = df_5['custno']
df_6.sort_values(by='Product_Sold',ascending=False).head()

"""Usecase-4 Display top 5 transactions amount from CSV_s1"""

df_7 = df_transactions.sort_values('amount',ascending=False)
df_7['amount'].head()

"""Usecase-5 Display distinct professions from CSV_s1

"""

df_customers['profession'].unique()

"""Usecase-6 Display highest age in CSV_s1 customer’s dataset

"""

df_customers['age'].max()

"""Usecase-7 Display custno, gender, age, profession, contactno, productno, productName,txndate, spendby, amount from CSV_s1 for custno=923

Usecase-8 Load all three PSV (pipe separated values) dataset in Pandas Data frames and
display first 5 records.
"""

from google.colab import files
import pandas as pd
data = files.upload()

df_customers_PSV = pd.read_csv('customers.txt',delimiter='|',names=customers_list)
df_customers.head(6)

df_products_PSV = pd.read_csv('products.txt',delimiter='|',names=products_list)
df_products.head(6)

df_transactions_PSV = pd.read_csv('transactions.txt',delimiter='|',names=transactions_list)
df_transactions.head(6)

"""Usecase-9 Load all three JSON datasets in Pandas Data frames and display first 5 records."""

from google.colab import files
import pandas as pd
data = files.upload()

df_customers_JSON = pd.read_json('customers.json',lines=True)
df_customers.head()

df_products_JSON = pd.read_json('products.json',lines=True)
df_products.head()

df_transactions_JSON = pd.read_json('transactions.json',lines=True)
df_transactions.head()

"""Usecase-10 Load all three XML datasets in Pandas Data frames and display first 5 records."""

from google.colab import files
import pandas as pd
data = files.upload()

df_cuxtomers_XML = pd.read_xml('customers.xml')
df_customers.head(6)

df_products_XML = pd.read_xml('products.xml')
df_products.head(6)

df_transactions_XML = pd.read_xml('transactions.xml')
df_transactions.head(6)